### ISSUE TITLE
(Official Server) Babscon 2015 Server open, is this project dead?

### ISSUE THREAD

**Issue by dlwh13** [tux3/LoE-PrivateServer#96]
BABSCon is coming up in April! For those of you going, we wish you a safe travel and a happy time down at the convention. If you haven't heard yet, we'll be making our way down there as well! You'll be able to meet and talk with the ponies who help make the game possible and prod them with thousands of questions.

If you're not joining us at BABSCon, fear not; you'll be able to enjoy our panel through the magic of the internet, where we'll be discussing all sorts of cool stuff about the game and perhaps leak some cool secrets!

Err, I mean, what secrets? We don't have any secrets!
Legends of Equestria does not comment on rumors and speculations relating to the game.

Mmm, yes, quite. Anyway, the panel happens at 1:30 PM PDT on Friday April 3rd so we hope to see everypony there!

After the convention, we hope you'll still have some room left for more fun! We're happy to announce that we'll be having another Open Server Event on April 10-12! It will be a chance to try out some cool new features we've been working on in the game, as well as experience all the content we've offered in the past. Just in case you missed any of it! We'll be providing more information, and the download links, closer to the event, so stay tuned!

April is going to be an exciting month for Legends of Equestria and we hope to see you all join us for the fun!

Now if you excuse me, I need to get ready to meet up with Golden Gates!
Hmm... Now where is my airship ticket...

Is this project dead? or some another guys continue this project?

**Comment by DanielOaks** [comment]
The problem is that LoE's networking was rewritten fairly extensively a while ago, and it takes lots of time and effort to update this project to work again (I know someone else doing similar work took a look at how much had been changed since the version this project implements, and decided that writing another new server entirely from scratch was more feasible than trying to adapt/update their old one).

If anyone's willing to spend the hours and hours reversing the new stuff, definitely! But I wouldn't hold your breath.

**Comment by PXke** [comment]
Does someone lead such a project ?
